### ISSUE TITLE
vCert playbook certificate fails to download when keyPassword is nil

### ISSUE THREAD

**Issue by BeardedPrincess** [Venafi/vcert#310]
**PROBLEM SUMMARY**
If keyPassword is excluded (or mistyped) the marshaling sets it to nil. When vCert attempts to download the certificate from TPP, it attempts to use nil as the password (or excludes it?) to protect the private key and fails.  However, passing the empty string `''` to keyPassword has logic to generate a one-time password to pull the private key from TPP.

**STEPS TO REPRODUCE**
Build a playbook file that excludes `keyPassword` when requesting a service generated certificate. 

```
certificates:
    - installations:
        - location: /etc/ssl/certs
          pemCertFilename: gray.pem
          pemChainFilename: gray-chain.pem
          pemKeyFilename: ../private/gray.key
          type: PEM
      name: myCertificate
      renewBefore: 10%
      request:
        csrOrigin: service
        keyPasswordIgnoreMeLikeIDontExist: anything
        subject:
            commonName: gray.lab.securafi.net
        zone: Certificates\vcertplus
```

**EXPECTED RESULTS**
When excluded, vCert should generate a one-time password for the purpose of downloading the private key, as it does if you set `keyPassword: ''`

**ACTUAL RESULTS**
API call fails to TPP, and vCert terminates with error

**ENVIRONMENT DETAILS**
vCert 5.0 preview (vcp)

**COMMENTS/WORKAROUNDS**
Related to https://github.com/Venafi/vcert/issues/309
