### ISSUE TITLE
vcert playbook fails to back up current certificate files

### ISSUE THREAD

**Issue by ChadKlunck** [Venafi/vcert#549]
**PROBLEM SUMMARY**
When renewing a certificate using a vcert playbook, and requesting "backupFiles: true", the backup files are created, but have no content (length of 0 bytes).

**STEPS TO REPRODUCE**
`vcert run -f /path/to/playbook.yaml >> /path/to/log`

Relevant parts of playbook.yaml:
```
certificateTasks:
  - name: Task name
    installations:
    - format: PEM
      file: /path/to/hostname.cer.pem
      keyFile: /path/to/hostname.key.pem
      chainFile: /path/to/chain.pem
      backupFiles: true
```

**EXPECTED RESULTS**
Existing *.pem files are copied to *.pem.bak, containing their original contents prior to executing the 'vcert' script

**ACTUAL RESULTS**
\*.pem.bak files are created, but all have a length of 0
Renewed certificate files (*.pem) are written properly

The issue appears to be at:
vcert/pkg/playbook/util/filehelper.go:77

```
sourceFile, err := os.Create(source)
...
destinationFile, err := os.Create(destination)
...
_, err = io.Copy(destinationFile, sourceFile)
```

This code appears to be _truncating_ the source file to 0 bytes, then copying the 0-byte file to the destination (.bak) file.

I think line 77 might have been intended to read:

```sourceFile, err := os.Open(source)```

**ENVIRONMENT DETAILS**
OS: RHEL 8
vcert version: 5.8.0

**COMMENTS/WORKAROUNDS**
Please sanity check the proposed solution; everything I know about Go I learned 5 minutes ago from a Google search
